services:
  mysqldb:
    image: mysql:8.0
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$SPRING_DATASOURCE_PASSWORD
      - MYSQL_DATABASE=$SPRING_DATASOURCE_URL
    ports:
      - $MYSQL_LOCAL_PORT:$MYSQL_DB_DOCKER_PORT
  app:
    depends_on:
      - mysqldb
    image: car-sharing-app
    restart: unless-stopped
    build: .
    env_file: ./.env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
      - $DEBUG_PORT:$DEBUG_PORT
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url" : "jdbc:mysql://mysqldb:$MYSQL_DB_DOCKER_PORT/$SPRING_DATASOURCE_URL?serverTimezone=UTC",
        "spring.datasource.username" : "$SPRING_DATASOURCE_USERNAME",
        "spring.datasource.password" : "$SPRING_DATASOURCE_PASSWORD",
        "spring.jpa.hibernate.ddl-auto" : "validate"
      }'
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:$DEBUG_PORT"
